/**
 * Model3DViewer — interactive 3D preview of a footprint.
 *
 * Renders as a plain `<img>` whose `src` is a PNG generated by kicad-cli
 * via the sidecar (NOT WebGL/three.js — WebKitGTK on Linux has unreliable
 * WebGL2; the alpha.18 SymbolPreview migration was driven by exactly this).
 *
 * Drag-to-orbit: the user drags the canvas to update internal azimuth /
 * elevation signals, which retrigger a debounced sidecar RPC that re-renders
 * the PNG with the new orbit. Live-preview transform values (offset,
 * rotation, scale) are passed through on every render so the user sees
 * unsaved positioner edits without disk writes.
 */

import { createEffect, createSignal, onCleanup, Show } from 'solid-js';
import { invoke } from '@tauri-apps/api/core';

type Triple = [number, number, number];

interface Props {
  libDir: string;
  componentName: string;
  /** Live (possibly unsaved) (model …) transform — patched into the
   *  spliced board in-memory by the sidecar so the user sees their
   *  positioner edits without saving to disk. */
  offset: Triple;
  rotation: Triple;
  scale: Triple;
  /** Bumped on positioner Save — forces a re-render even when offset/rotation/scale
   *  are byref-equal (e.g. after a refetch returned the same numbers). */
  savedRev: number;
}

export default function Model3DViewer(props: Props) {
  const [azimuth, setAzimuth] = createSignal(-25);
  const [elevation, setElevation] = createSignal(-25);
  const [dragStart, setDragStart] = createSignal<
    { x: number; y: number; az: number; el: number } | null
  >(null);
  const [imgSrc, setImgSrc] = createSignal('');
  const [rendering, setRendering] = createSignal(false);
  // Wheel zoom — pure CSS transform on the <img>, no sidecar round-trip.
  // Clamped to [0.4, 4.0] for sane bounds.
  const [zoom, setZoom] = createSignal(1.0);

  const clamp = (v: number, lo: number, hi: number) =>
    Math.max(lo, Math.min(hi, v));

  // Window-level move/up listeners are attached only while dragging so a
  // fast orbit whose cursor leaves the canvas still tracks smoothly, and
  // the user can release anywhere to end the drag.
  const handleWindowMouseMove = (e: MouseEvent) => {
    const start = dragStart();
    if (!start) return;
    const dx = e.clientX - start.x;
    const dy = e.clientY - start.y;
    // Orbit feel: 1 px ≈ 0.5° so a slow swipe rotates ~90°.
    setAzimuth(start.az + dx * 0.5);
    const newEl = start.el + dy * 0.5;
    setElevation(Math.max(-85, Math.min(85, newEl)));
  };

  const handleWindowMouseUp = () => {
    setDragStart(null);
    window.removeEventListener('mousemove', handleWindowMouseMove);
    window.removeEventListener('mouseup', handleWindowMouseUp);
  };

  const handleMouseDown = (e: MouseEvent) => {
    // preventDefault is the load-bearing line: without it, the browser
    // initiates a text selection from the mousedown point, which causes
    // jagged paint while orbiting.
    e.preventDefault();
    e.stopPropagation();
    setDragStart({ x: e.clientX, y: e.clientY, az: azimuth(), el: elevation() });
    window.addEventListener('mousemove', handleWindowMouseMove);
    window.addEventListener('mouseup', handleWindowMouseUp);
  };

  const handleWheel = (e: WheelEvent) => {
    e.preventDefault();
    setZoom((z) => clamp(z * (e.deltaY < 0 ? 1.1 : 0.9), 0.4, 4));
  };

  // Debounced re-render: any change to orbit, transform, or savedRev
  // re-fires the sidecar RPC after a 100 ms quiet period. Keeps the wire
  // calm during drag without making the preview feel laggy.
  let pending: number | undefined;
  createEffect(() => {
    // Tracked deps:
    azimuth();
    elevation();
    props.offset;
    props.rotation;
    props.scale;
    props.savedRev;
    props.libDir;
    props.componentName;

    if (pending !== undefined) clearTimeout(pending);
    pending = window.setTimeout(async () => {
      setRendering(true);
      try {
        const r = await invoke<{ png_data_url: string }>('sidecar_call', {
          method: 'library.render_3d_png_angled',
          params: {
            lib_dir: props.libDir,
            component_name: props.componentName,
            azimuth: azimuth(),
            elevation: elevation(),
            offset: props.offset,
            rotation: props.rotation,
            scale: props.scale,
            width: 600,
            height: 400,
          },
        });
        setImgSrc(r.png_data_url);
      } catch (e) {
        console.warn('[3D viewer] render failed:', e);
      } finally {
        setRendering(false);
      }
    }, 100);
  });

  onCleanup(() => {
    if (pending !== undefined) clearTimeout(pending);
    // Remove any window listeners still attached if the component unmounts
    // mid-drag — otherwise we'd leak handlers that reference stale signals.
    window.removeEventListener('mousemove', handleWindowMouseMove);
    window.removeEventListener('mouseup', handleWindowMouseUp);
  });

  return (
    <div
      data-testid="3d-viewer-canvas"
      onMouseDown={handleMouseDown}
      onWheel={handleWheel}
      style={{
        width: '100%',
        height: '240px',
        'max-width': 'none',
        cursor: dragStart() ? 'grabbing' : 'grab',
        'user-select': 'none',
        '-webkit-user-select': 'none',
        position: 'relative',
      }}
      class="rounded overflow-hidden bg-white dark:bg-zinc-950"
    >
      <img
        data-testid="3d-viewer-img"
        attr:data-zoom={String(zoom())}
        src={imgSrc()}
        alt=""
        draggable={false}
        style={{
          'object-fit': 'contain',
          width: '100%',
          height: '100%',
          'pointer-events': 'none',
          transform: `scale(${zoom()})`,
          'transform-origin': 'center center',
        }}
      />
      <Show when={rendering() && !imgSrc()}>
        <div
          class="absolute inset-0 flex items-center justify-center text-xs text-zinc-500 dark:text-zinc-400 bg-zinc-200/60 dark:bg-zinc-800/60"
          style={{ 'pointer-events': 'none' }}
        >
          Rendering 3D…
        </div>
      </Show>
    </div>
  );
}
